version: '3.8'

services:
  server:
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app

  client:
    build:
      dockerfile: ../client/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../client:/usr/src/app
