version: '3.8'

services:
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app

  client:
    build: ../client
    ports:
      - "3000:3000"
    volumes:
      - ../client:/usr/src/app
